---
name: Create Debian Packages

on:  # yamllint disable-line rule:truthy
    release:
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
        types: [published]
    workflow_dispatch:  # Allow to be triggered manually for now.

permissions:
    contents: read  # to fetch code (actions/checkout)

jobs:
    update-changelog:
        env:
            CHANGELOG_AUTHOR_NAME: "Scott Laird"
            CHANGELOG_AUTHOR_EMAIL: "scott@sigkill.org"
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

            - name: Checkout code again
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Patch changelog (snapshot)
              id: bump_changelog
              env:
                  DEBEMAIL: ${{ env.CHANGELOG_AUTHOR_EMAIL }}
                  DEBFULLNAME: ${{ env.CHANGELOG_AUTHOR_NAME }}
              run: |
                  set -e
                  sudo apt --yes --quiet install git-buildpackage
                  echo "GITHUB_REF=${GITHUB_REF}"
                  gbp dch --release -N ${GITHUB_REF:11}

            - name: Determine current version
              run: |
                  sudo apt install -y dpkg-dev
                  echo "CURRENT_VERSION=$(dpkg-parsechangelog -Sversion)" >> $GITHUB_ENV

            - name: Submit the last change to Git
              run: |
                  # from https://gist.github.com/Broxzier/1ed980b8b3822d213e98042fc6a92040
                  git config --global user.email "scott+github-bot@sigkill.org"
                  git config --global user.name "LinucCNC-Ethercat git bot"
                  git add debian/changelog
                  git commit --amend --no-edit  # -m 'Automatically update debian/changelog for ${{ env.CURRENT_VERSION }}'
                  git push
                  echo "complete"

    # This is mostly copied from LinuxCNC's ci.yml as well.
    build-debian-packages:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                image:
                    - "debian:buster"
                    #- "debian:bullseye"
                    #- "debian:bookworm"
                    #- "debian:sid"
                #arch:
                #  - amd64
        env:
            DEBEMAIL: scott@sigkill.org
            DEBFULLNAME: LinuxCNC-EtherCAT Github CI Robot
            DEBIAN_FRONTEND: noninteractive
        container:
            image: ${{ matrix.image }}
            # IPC_OWNER is needed for shmget IPC_CREAT
            # SYS_ADMIN is needed for shmctl IPC_SET
            options: --cpus=2 --cap-add=IPC_OWNER --cap-add=SYS_ADMIN
        steps:
            - name: Add linuxcnc.org deb archive
              env:
                  DEBIAN_FRONTEND: noninteractive
              run: |
                  set -e
                  set -x

                  apt --quiet update
                  apt --yes --quiet install --no-install-recommends gpg software-properties-common git docker.io sudo dpkg-dev curl devscripts

                  apt --yes --quiet install --no-install-recommends gpg software-properties-common
                  git clone https://github.com/LinuxCNC/linuxcnc.git linuxcnc
                  gpg --homedir="${PWD}/linuxcnc/gnupg" --output /etc/apt/trusted.gpg.d/linuxcnc-deb-archive.gpg --export 3CB9FD148F374FEF
                  DIST=$(echo ${{matrix.image}} | cut -d : -f 2)
                  add-apt-repository "deb http://linuxcnc.org $DIST 2.9-uspace"
                  apt --quiet update

            # Add repositories from build.opensuse.org which provides EtherCAT master
            - name: Add build.opensuse.org Ethercat deb archive
              env:
                  DEBIAN_FRONTEND: noninteractive
              run: |
                  set -e
                  set -x

                  case "${{matrix.image}}" in
                  debian:sid)
                    echo "deb [signed-by=/usr/share/keyrings/ethercat.gpg] http://download.opensuse.org/repositories/science:/EtherLab/Debian_Unstable/ ./"> etherlab.list
                    ;;
                  debian:bookworm)
                    echo "deb [signed-by=/usr/share/keyrings/ethercat.gpg] http://download.opensuse.org/repositories/science:/EtherLab/Debian_12/ ./"> etherlab.list
                    ;;
                  debian:bullseye)
                    echo "deb [signed-by=/usr/share/keyrings/ethercat.gpg] http://download.opensuse.org/repositories/science:/EtherLab/Debian_11/ ./"> etherlab.list
                    ;;
                  debian:buster)
                    echo "deb [signed-by=/usr/share/keyrings/ethercat.gpg] http://download.opensuse.org/repositories/science:/EtherLab/Debian_10/ ./"> etherlab.list
                    ;;
                  esac

                  sudo cp etherlab.list /etc/apt/sources.list.d/etherlab.list
                  curl -fsSL "https://build.opensuse.org/projects/science:EtherLab/signing_keys/download?kind=gpg" | gpg --dearmor > ec.gpg
                  sudo cp ec.gpg /usr/share/keyrings/ethercat.gpg

                  apt --quiet update
                  apt --yes --quiet install ethercat-master libethercat-dev libpdserv3-dev librtipc-dev etherlab

            - name: Install pre-dependencies
              env:
                  DEBIAN_FRONTEND: noninteractive
              run: |
                  set -e
                  set -x
                  apt --yes --quiet install linuxcnc-uspace
                  apt --yes --quiet install yapps2

            - name: Checkout
              uses: actions/checkout@v3
              with:
              # "fetch-depth: 0" fetches all of history, this is needed by
              # our build system to determine the version from tags
                  fetch-depth: 0

            - name: Determine current version
              run: |
                  echo "CURRENT_VERSION=$(dpkg-parsechangelog -Sversion)" >> $GITHUB_ENV

            - name: Build architecture-specific Debian packages
              run: |
                  set -e
                  set -x
                  git config --global --add safe.directory "${PWD}"
                  #debian/configure
                  #debian/update-dch-from-git
                  #scripts/get-version-from-git | sed -re 's/^v(.*)$/\1/' >| VERSION; cat VERSION
                  echo ${{ env.CURRENT_VERSION }}
                  git diff
                  apt --yes --quiet build-dep --arch-only .
                  debuild -us -uc --build=any

            - name: Test debian packages
              env:
                  DEBIAN_FRONTEND: noninteractive
              run: |
                  set -e
                  set -x
                  apt --yes --quiet install ../*.deb

            - name: Upload linuxcnc-ethercat .deb to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: ../linuxcnc-ethercat_${{ env.CURRENT_VERSION }}_amd64.deb
                  asset_name: deb/${{ matrix.image }}/mything
                  overwrite: true
                  make_latest: false

            - name: Upload linuxcnc-ethercat-dbgsym .deb to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: ../linuxcnc-ethercat-dbgsym_${{ env.CURRENT_VERSION }}_amd64.deb
                  asset_name: deb/${{ matrix.image }}/mything
                  overwrite: true
                  make_latest: false

